import { IndentationAwareLexer, type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { createTypirLangiumServices, initializeLangiumTypirServices, type TypirLangiumServices } from 'typir-langium';
import { BookshelfDocGeneratedModule, BookshelfDocGeneratedSharedModule } from './generated/module.js';
import { reflection } from './generated/ast.js';
import { BookshelfDocCompletionProvider } from './bookshelf-doc-completion.js';
import { BookshelfDocSemanticTokenProvider } from './bookshelf-doc-semantic-tokens.js';
import { BookshelfDocTokenBuilder } from './bookshelf-doc-token-builder.js';
import { BookshelfDocTypeSystem, type BookshelfDocSpecifics } from './bookshelf-doc-typir.js';
import { BookshelfDocValidator, registerValidationChecks } from './bookshelf-doc-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type BookshelfDocAddedServices = {
    validation: {
        BookshelfDocValidator: BookshelfDocValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type BookshelfDocServices = LangiumServices & BookshelfDocAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const BookshelfDocModule: Module<BookshelfDocServices, PartialLangiumServices & BookshelfDocAddedServices> = {
    validation: {
        BookshelfDocValidator: () => new BookshelfDocValidator()
    },
    parser: {
        TokenBuilder: () => new BookshelfDocTokenBuilder({
            // a struct is the one place where line breaks carry no meaning
            ignoreIndentationDelimiters: [ ['{', '}'] ]
        }),
        Lexer: (services) => new IndentationAwareLexer(services)
    },
    lsp: {
        CompletionProvider: (services) => new BookshelfDocCompletionProvider(services),
        SemanticTokenProvider: (services) => new BookshelfDocSemanticTokenProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createBookshelfDocServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    BookshelfDoc: BookshelfDocServices,
    typir: TypirLangiumServices<BookshelfDocSpecifics>
} {
    const shared = inject(
        createDefaultSharedModule(context),
        BookshelfDocGeneratedSharedModule
    );
    const BookshelfDoc = inject(
        createDefaultModule({ shared }),
        BookshelfDocGeneratedModule,
        BookshelfDocModule
    );
    shared.ServiceRegistry.register(BookshelfDoc);
    registerValidationChecks(BookshelfDoc);
    const typir = createTypirLangiumServices<BookshelfDocSpecifics>(shared, reflection, new BookshelfDocTypeSystem());
    initializeLangiumTypirServices(BookshelfDoc, typir);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, BookshelfDoc, typir };
}
