import { inject, type Module } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { createTypirLangiumServices, initializeLangiumTypirServices, type TypirLangiumServices } from 'typir-langium';
import { BsdocGeneratedModule, BsdocGeneratedSharedModule } from './generated/module.js';
import { reflection } from './generated/ast.js';
import { BsdocCompletionProvider } from './bsdoc-completion.js';
import { BsdocFoldingRangeProvider } from './bsdoc-folding.js';
import { BsdocHoverProvider } from './bsdoc-hover.js';
import { BsdocLexer } from './bsdoc-lexer.js';
import { BsdocScopeComputation } from './bsdoc-scope.js';
import { BsdocSemanticTokenProvider } from './bsdoc-semantic-tokens.js';
import { BsdocTokenBuilder } from './bsdoc-token-builder.js';
import { BsdocProblemPrinter, BsdocTypeSystem, type BsdocSpecifics } from './bsdoc-typir.js';
import { BsdocValidator, registerValidationChecks } from './bsdoc-validator.js';
import { BsdocValueConverter } from './bsdoc-value-converter.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type BsdocAddedServices = {
    validation: {
        BsdocValidator: BsdocValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type BsdocServices = LangiumServices & BsdocAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const BsdocModule: Module<BsdocServices, PartialLangiumServices & BsdocAddedServices> = {
    validation: {
        BsdocValidator: () => new BsdocValidator()
    },
    parser: {
        TokenBuilder: () => new BsdocTokenBuilder(),
        Lexer: (services) => new BsdocLexer(services),
        ValueConverter: () => new BsdocValueConverter()
    },
    references: {
        ScopeComputation: (services) => new BsdocScopeComputation(services),
    },
    lsp: {
        CompletionProvider: (services) => new BsdocCompletionProvider(services),
        FoldingRangeProvider: (services) => new BsdocFoldingRangeProvider(services),
        HoverProvider: (services) => new BsdocHoverProvider(services),
        SemanticTokenProvider: (services) => new BsdocSemanticTokenProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createBsdocServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Bsdoc: BsdocServices,
    typir: TypirLangiumServices<BsdocSpecifics>
} {
    const shared = inject(
        createDefaultSharedModule(context),
        BsdocGeneratedSharedModule
    );
    const Bsdoc = inject(
        createDefaultModule({ shared }),
        BsdocGeneratedModule,
        BsdocModule
    );
    shared.ServiceRegistry.register(Bsdoc);
    registerValidationChecks(Bsdoc);
    const typir = createTypirLangiumServices<BsdocSpecifics>(shared, reflection, new BsdocTypeSystem(), {
        Printer: () => new BsdocProblemPrinter(),
    });
    initializeLangiumTypirServices(Bsdoc, typir);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Bsdoc, typir };
}
